# azure-pipelines.yml
trigger:
- master  # Trigger the pipeline when changes are pushed to the main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "Hello, Azure DevOps Pipeline!"
  displayName: 'Run a simple script'