pool:
  vmImage: windows-latest

# variables:
# - name: myshare
#   value: filetodelete
# - name: accountname
#   value: mystorage616
# - name: accountkey
#   value: kHX64beg95HB/H0dD7IE0vv3+pRCMsdGnJFyjVP8GRIj2prvRLscEletnKplxF6MOEJdinVS30SL+AStTzBCdA==

trigger: none
pr: none
stages:
  - stage: 
    jobs:
      - job:
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              $myshare = "mystorageshare"
                $accountName = "mystorageac"
                $accountKey = "+lVt/N8Ld+90afGetaq8Ko5CUvHr47ZDqnA9O1fOXtExq9YMhBLNNHrXoPAJn/tDuqjzJwh1ymg3+AStjXSntg=="
              
                $filelist = az storage file list -s $myshare --account-name $accountName --account-key $accountKey
              
                $fileArray = $filelist | ConvertFrom-Json
                foreach ($file in $fileArray | Where-Object {$_.properties.lastModified.DateTime -lt ((Get-Date).AddDays(-90))})
                    {
                        $removefile = $file.name
                        if ($removefile -ne $null)
                        {
                            Write-Host "Removing file $removefile"
                            az storage file delete -s $myshare -p $removefile --account-name $accountName --account-key $accountKey
                        }
                    }
            pwsh: true