pool:
  vmImage: ubuntu-latest

variables:
- name: myshare
  value: filetodelete
- name: accountname
  value: mystorage616
- name: accountkey
  value: kHX64beg95HB/H0dD7IE0vv3+pRCMsdGnJFyjVP8GRIj2prvRLscEletnKplxF6MOEJdinVS30SL+AStTzBCdA==

trigger: none
pr: none
stages:
  - stage: 
    jobs:
      - job:
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Azure subscription 1(0bb04acb-8639-4207-ab1c-2cbab5516176)'
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: |
                $filelist = az storage file list -s $myshare --account-name $accountName --account-key $accountKey
                Write-Host $filelist
                    $fileArray = $filelist | ConvertFrom-Json
                    foreach ($file in $fileArray | Where-Object {$_.properties.lastModified.DateTime -lt ((Get-Date).AddDays(0))})
                    {
                        $removefile = $file.name
                        if ($removefile -ne $null)
                        {
                            Write-Host "Removing file $removefile"
                            az storage file delete -s $myshare -p $removefile
                        }
                    }
              addSpnToEnvironment: true
              useGlobalConfig: true