trigger: none

pr: none

stages:
  - stage: Build_test
    jobs:
      - job: installer
        steps:
          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                java --version
                mvn --version

          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                mvn clean
          
  - stage: test_deploy
    condition: failed()
    jobs:
      - job: install
        steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo Write your commands here
                
                echo Hello world

  - stage: test1_deploy
    jobs:
      - job: install
        steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo Write your commands here
                
                echo Hello world again              