trigger: none

pr: none

stages:
  - stage: Build_test
    jobs:
      - job: installer
        steps:
          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                java --version
                mvn --version

          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                mvn clean
                mvn install
  - stage: test_deploy
    jobs:
      - job: install
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
            # Write your commands here
            
         echo 'Hello world'

  - stage: test_build
    jobs:
      - job: install
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
                script: |
              # Write your commands here
                
        echo 'Hello world'