trigger: none

pr: none

stages:
  - stage: installjava
      # variables:
      # - group: devv-variable-group
    jobs: 
      - job: installer
        steps: 
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |              
              java --version
              mvn --version
        
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |              
              mvn clean
              mvn install


  # - stage: install the script
  #   jobs:
  #     - job: installer
  #       steps:
  #       - task: ShellScript@2
  #         inputs:
  #           scriptPath: 'install.sh'       

  # - stage: Start the script
  #   jobs:
  #     - job: installer
  #       steps:
  #       - task: ShellScript@2
  #         inputs:
  #           scriptPath: 'start.sh' 

  # - stage: Deply to static web
  #   jobs:
  #    - job: deploy
  #      steps:
  #      - task: AzureStaticWebApp@0
  #        inputs:
  #          app_location: 'src'
  #          output_location: 'private'
  #          azure_static_web_apps_api_token: $(storybook-mock-api-key)