pool:
  vmImage: windows-latest

variables:
- name: myshare
  value: filetodelete
- name: accountname
  value: 6mystorageaccount
- name: accountkey
  value: kHX64beg95HB/H0dD7IE0vv3+pRCMsdGnJFyjVP8GRIj2prvRLscEletnKplxF6MOEJdinVS30SL+AStTzBCdA==

trigger: none
pr: none
stages:
  - stage: 
    jobs:
      - job:
        steps:
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: 'Azure subscription 1(0bb04acb-8639-4207-ab1c-2cbab5516176)'
              ScriptType: 'InlineScript'
              Inline: |
                # az storage file list -s $myshare --account-name $accountName --account-key $accountKey
                $filelist = az storage file list -s $myshare --account-name $accountName --account-key $accountKey
                    $fileArray = $filelist | ConvertFrom-Json
                    foreach ($file in $fileArray | Where-Object {$_.properties.lastModified.DateTime -lt ((Get-Date).AddDays(-1))})
                    {
                        $removefile = $file.name
                        if ($removefile -ne $null)
                        {
                            Write-Host "Removing file $removefile"
                            az storage file delete -s $myshare -p $removefile
                        }
                    }
                preferredAzurePowerShellVersion: 1.0.1