name: Trigger auto deployment for mysrk123

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/mysrk123-AutoDeployTrigger-ae1164b3-9046-47d2-8c18-b628a31b9013.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.MYSRK123_REGISTRY_USERNAME }}
          password: ${{ secrets.MYSRK123_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: venkat143/mysrk123:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MYSRK123_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n mysrk123 -g mysuccess6 --server docker.io --username  ${{ secrets.MYSRK123_REGISTRY_USERNAME }} --password ${{ secrets.MYSRK123_REGISTRY_PASSWORD }}
            az containerapp update -n mysrk123 -g mysuccess6 --image venkat143/mysrk123:${{ github.sha }}
